#!/bin/bash
pushd /opt/intel
    . venv/bin/activate
    (python3 app.py) >> /opt/intel/start.log
    sleep 10
popd
chromium-browser --kiosk --touch-events=enabled --disable-pinch --noerrdialogs --disable-session-crashed-bubble --app=$(head -n 1 /boot/fullpageos.txt)
